#!/j/src/bin/perl -s
($k,$n)=@ARGV;$m=unpack(H.$w,$m."\0"x$w),$_=`echo "16do$w 2+4Oi0$d*
-^1[d2%Sa2/d0<X+d*La1=z\U$n%0]SX$k"[$m*]\EszlXx++p|dc`,s/^.|\W//g,
print pack('H*',$_)while read(STDIN,$m,($w=2*$d-1+length($n)&~1)/2)
